site_name: Documentation
theme:
  name: material
  font: false
  palette:
    primary: indigo
    accent: indigo

nav:

  - Home: index.md

plugins:
  - include-markdown
  - search

#extra_css:
#  - 'stylesheets/extra.css'


markdown_extensions:

  - codehilite
  - markdown.extensions.admonition
  - pymdownx.arithmatex
  - pymdownx.extra
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tabbed
